package com.example.navigationcollectiontuto

import android.os.Bundle
import android.view.View
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import kotlinx.android.synthetic.main.fragment_home.*

class HomeFragment : Fragment(R.layout.fragment_home) {

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        //Have to rebuild project if first time adding the view

        //This is manual navigation with buttons and stuff
        btnLogin.setOnClickListener {
            //Generated by the navGraph arrow
            //Compile safe
            val action = HomeFragmentDirections.actionHomeFragmentToLoginFragment()
            findNavController().navigate(action)

            // other option
            //findNavController().navigate(R.id.action_homeFragment_to_loginFragment)
        }
    }

}